services:
  # -------------------------
  # App Service
  # -------------------------
  app_service:
    build:
      context: ./backend/app_service
    image: agri-vision/backend/app_service:latest
    container_name: agri_vision_app_service
    ports:
      - "8000:8000"
    env_file: ./backend/app_service/.env
    environment:
      - PROMETHEUS_MULTIPROC_DIR=/tmp/prometheus_multiproc

  # -------------------------
  # Model Service
  # -------------------------
  model_service:
    build:
      context: ./backend/model_service
    image: agri-vision/backend/model_service:latest
    container_name: agri_vision_model_service
    ports:
      - "8002:8002"
    env_file: ./backend/model_service/.env
    environment:
      - PROMETHEUS_MULTIPROC_DIR=/tmp/prometheus_multiproc

  # -------------------------
  # Frontend (Vite React + Nginx)
  # -------------------------
  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: /api/v1
        VITE_MODEL_API_URL: /model/v1
    image: agri-vision/frontend:latest
    container_name: agri_vision_frontend_service
    ports:
      - "3000:80"
    depends_on:
      - app_service
      - model_service


  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./backend/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - app_service
      - model_service

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    depends_on:
      - prometheus

volumes:
  grafana_data:
