services:
  # -------------------------
  # App Service
  # -------------------------
  app_service:
    image: ${APP_NAME}_app:${GIT_COMMIT}
    container_name: app_service
    ports:
      - "8000:8000"
    env_file: ./backend/app_service/.env

  # -------------------------
  # Model Service
  # -------------------------
  model_service:
    image: ${APP_NAME}_model:${GIT_COMMIT}
    container_name: model_service
    ports:
      - "8002:8002"
    env_file: ./backend/model_service/.env

  # -------------------------
  # Frontend (Vite React + Nginx)
  # -------------------------
  frontend:
    image: ${APP_NAME}_frontend:${GIT_COMMIT}
    container_name: frontend_service
    ports:
      - "3000:80"
    depends_on:
      - app_service
      - model_service