
services:
  # -------------------------
  # App Service
  # -------------------------
  app_service:
    build: ./backend/app_service
    container_name: app_service
    ports:
      - "8000:8000"
    env_file: ./backend/app_service/.env

  # -------------------------
  # Model Service
  # -------------------------
  backend2:
    build: ./backend/model_service
    container_name: model_service
    ports:
      - "8002:8002"
    env_file: ./backend/model_service/.env
  # -------------------------
  # Frontend (Vite React + Nginx)
  # -------------------------
  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://backend1:8000
        VITE_MODEL_API_URL: http://backend2:8002
    container_name: frontend_service
    ports:
      - "3000:80"
    depends_on:
      - app_service
      - model_service
