from pydantic import BaseModel, Field
from datetime import datetime, timezone
from enum import Enum
from typing import Optional

# Enum for model status
class ModelStatus(str, Enum):
    active = "active"
    inactive = "inactive"
    deprecated = "deprecated"

class Model(BaseModel):
    id: str  # UUID4 generated by backend
    name: str  # e.g., "ResNet", "EfficientNet"
    version: str  # e.g., "v1.0"
    description: Optional[str] = None
    container_name: str  # Docker container name
    endpoint: str  # URL/path to call this model service
    status: ModelStatus = ModelStatus.active
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))

    class Config:
        json_encoders = {
            datetime: lambda dt: dt.isoformat()
        }
