[project]
name = "db-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.2"
dependencies = [
    "motor==3.7.1",
    "pydantic-settings==2.10.1",
]
